### ISSUE TITLE
Add ability to update settings.json

### ISSUE THREAD

**Issue by eraserix** [gantsign/ansible-role-visual-studio-code#134]
I'd like to add user specific settigns to settings.json, e.g. update the file with additional settings once it has been written (or even overwrite existing setttings).
Background: We provide a default setup of vscode to all team members, but things like the theme are pretty much down to each users preferences.

**Comment by eraserix** [comment]
To update settings.json, I ended up with the code below. It appears to do what I want it to:

```yaml
- name: delete comments from settings.json (from_json breaks with comments)
  lineinfile:
    dest: "{{ ansible_user_dir }}/.config/Code/User/settings.json"
    state: absent
    regexp: "^//"

- name: read current settings.json
  slurp: src="{{ ansible_user_dir }}/.config/Code/User/settings.json"
  register: vscode_settings_file

- name: decode settings to json
  set_fact:
    vscode_settings: "{{ vscode_settings_file.content | b64decode | from_json }}"

- name: update settings
  set_fact:
    vscode_settings: "{{ vscode_settings | combine( vscode_additional_settings ) }}"
  vars:
    vscode_additional_settings: {
      "editor.renderWhitespace": "all",
      "workbench.colorTheme": "Visual Studio Light",
      "workbench.editor.enablePreview": false,
      "workbench.editor.enablePreviewFromQuickOpen": false,
    }

- name: write updated settings.json
  copy:
    dest: "{{ ansible_user_dir }}/.config/Code/User/settings.json"
    content: "{{ vscode_settings | to_nice_json }}\n"
```
