### ISSUE TITLE
APT requirements causing a failure

### ISSUE THREAD

**Issue by 1337-42** [gantsign/ansible-role-visual-studio-code#243]
When using the role on a recent Kali image you would encounter a error during the dependency installation:

```
TASK [ansible-role-visual-studio-code : Install dependencies (apt)] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'gconf2' is available"}
```

Installing most of the dependencies is not necessary at this step and will be handled by apt at the time of installation. Only `ca-certificates` and `apt-transport-https` ar required. I would suggest changing the task to something like this:

```yaml
- name: Install dependencies (apt)
  become: yes
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
    state: present
```
