### ISSUE TITLE
[Feature Request] Support deb822 apt format

### ISSUE THREAD

**Issue by deosrc** [gantsign/ansible-role-visual-studio-code#259]
Upgrading to Ubuntu 24.04 has converted all of my apt repository source files to the deb822 format. This results in this role showing a change to create the source file again in the older format, and there would then be 2 source files for the same repository. I have not checked with this role, but for another apt repository, this caused apt to break due to conflicting files.

I believe apt can (and has for a while) support both formats. I'm not sure if there is a good way to check which is the preferred format automatically, as I'm not sure if it's an apt or OS decision. Perhaps just a variable for now which defaults to the older format for compatibility?

Related ansible action: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/deb822_repository_module.html

**Comment by deosrc** [comment]
I have updated my playbook to use the below:

```yaml
- name: Add VSCode deb822 apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: vscode
    types: deb
    uris: https://packages.microsoft.com/repos/code
    suites: stable
    components: main
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
```

Which generates the `/etc/apt/sources.list..d/vscode.sources` file:

```text
X-Repolib-Name: vscode
Types: deb
URIs: https://packages.microsoft.com/repos/code
Suites: stable
Components: main
Signed-By: /etc/apt/keyrings/vscode.asc
```

Note that the key file is automatically downloaded and stored in the correct location by the `deb822_repository` action.
